#!/bin/sh
#
# Set sysctl values
#

case "$1" in
  start)
	echo "Setting sysctl values..."
	sysctl -p
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
