#!/bin/sh
#
# Set firewall rules
#

case "$1" in
  start)
	echo "Setting firewall rules..."
	iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
	iptables -P FORWARD DROP
	iptables -A FORWARD -i eth0 -o wlan0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
	iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
	iptables -P INPUT DROP
	iptables -A INPUT -i eth0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
	iptables -A INPUT -i wlan0 -j ACCEPT
	;;
  stop)
	iptables -F
	iptables -X
	iptables -t nat -F
	iptables -t nat -X
	iptables -t mangle -F
	iptables -t mangle -X
	iptables -t raw -F
	iptables -t raw -X
	iptables -P INPUT ACCEPT
	iptables -P FORWARD ACCEPT
	iptables -P OUTPUT ACCEPT
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
